apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: certbot
  namespace: default
  labels:
    component: cluster
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      component: certbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: certbot
    spec:
      containers:
      - name: certbot
        image: underscorenygren/kubernetes-certbot:latest
        resources:
          requests:
            cpu: 100m
            memory: 10M
          limits:
            cpu: 500m
            memory: 50M
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: "letsencrypt-config"
              key: domain
        - name: SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: "website"
              key: "cluster_name"
        - name: NO_SUBDOMAIN
          valueFrom:
            configMapKeyRef:
              name: "letsencrypt-config"
              key: no_subdomain
        - name: ELB_NAME
          valueFrom:
            configMapKeyRef:
              name: "letsencrypt-config"
              key: elb_name
        - name: STAGING
          valueFrom:
            configMapKeyRef:
              name: "letsencrypt-config"
              key: staging
        - name: LETS_ENCRYPT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: "letsencrypt-config"
              key: email
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "letsencrypt-aws"
              key: "key"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "letsencrypt-aws"
              key: "secret"
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: "letsencrypt-aws"
              key: "region"
        volumeMounts:
              - mountPath: /etc/letsencrypt
                name: letsencrypt-data
      volumes:
        - name: letsencrypt-data
          emptyDir: {}
