apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    component: cluster
spec:
  selector:
    component: certbot
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
